server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
              # 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
              # 匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-COM.LIS1.SPRINGCLOUD.SERVICE # 匹配后提供的动态路由地址
              # 断言，路径相匹配的进行路劲
          predicates:
            - Path=/payment/get/**

              # 路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh2
              # 匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-COM.LIS1.SPRINGCLOUD.SERVICE # 匹配后提供的动态路由地址
          # 断言，路径相匹配的进行路劲
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      # 表示是否将自己注册进EurekaServer 默认为true
      register-with-eureka: true
        # 是否从EurekaServer抓取已有注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
