server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com # eureka服务端的实例名称
  client:
    # 指定是否将服务注册到注册中心(注册中心不需要开启)
    register-with-eureka: false
    # 指定是否从注册中心获取服务(注册中心不需要开启)
    fetch-registry: false
    serviceUrl:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 集群指向其他eureka
#      defaultZone: http://eureka7002.com:7002/eureka
      # 单机指向自己
      defaultZone: http://eureka7001.com:7001/eureka
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除（此配置项默认为true）
#    enable-self-preservation: false

