server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment


eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true    # 访问路径可以显示IP地址
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
  #    lease-renewal-interval-in-seconds: 1
  #    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
  #    lease-expiration-duration-in-seconds: 2
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    serviceUrl:
      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://localhost:7001/eureka
