server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hysterix-order-com.lis1.springcloud.service


eureka:
  instance:
    instance-id: cloud-consumer-feign-hystrix-order80
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    serviceUrl:
      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://localhost:7001/eureka


